package UI;

import Lexer.Analex;
import Lexer.Cinta;
import java.awt.Color;
import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter.HighlightPainter;

public class Interfaz extends javax.swing.JFrame {
    private Cinta cinta;
    private Analex analex;
    
    public Interfaz() {
        initComponents();
        cinta = new Cinta();
        
        analex = new Analex(cinta){
            @Override
            public void comunicate(int pos, String lexema){
                Interfaz.this.resaltar(pos, lexema.length());
            }
        };
    }

//----------------------------------
    private void resaltar(int pos, int longitud){
        desResaltar();
        HighlightPainter colorResaltado = new DefaultHighlighter.DefaultHighlightPainter(Color.pink);
        
        try {
           textArea.getHighlighter().addHighlight(pos, pos+longitud, colorResaltado); 
        } catch (Exception e) {}
    }
    
    private void desResaltar(){
        textArea.getHighlighter().removeAllHighlights();
    }
//----------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        btnInit = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        tfPreanalisis = new javax.swing.JTextField();
        tfLexema = new javax.swing.JTextField();
        lblLexema = new javax.swing.JLabel();
        lblPreanalisis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        btnInit.setText("Init");
        btnInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitClick(evt);
            }
        });

        btnOpen.setText("Open...");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnAvanzar.setText("Avanzar");
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });

        tfPreanalisis.setEditable(false);
        tfPreanalisis.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfPreanalisis.setForeground(java.awt.Color.blue);
        tfPreanalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPreanalisisActionPerformed(evt);
            }
        });

        tfLexema.setEditable(false);

        lblLexema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLexema.setText("Lexema");

        lblPreanalisis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPreanalisis.setText("Preanálisis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnInit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLexema)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAvanzar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfPreanalisis)
                                .addComponent(tfLexema))
                            .addComponent(lblPreanalisis))))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnOpen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnOpen)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInit)
                        .addGap(43, 43, 43)
                        .addComponent(btnAvanzar)
                        .addGap(46, 46, 46)
                        .addComponent(lblPreanalisis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPreanalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lblLexema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLexema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInitClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitClick
        cinta.init(textArea.getText());
        analex.init();
        analex.resaltar();
        
        tfPreanalisis.setText(""+analex.Preanalisis());
        tfLexema.setText(analex.lexema());
            
    }//GEN-LAST:event_btnInitClick

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
            //Cargar un archivo al textArea ("Editor")
        JFileChooser fileChooser = new JFileChooser(".");
        fileChooser.showOpenDialog(this);
        
        try{
            File f = fileChooser.getSelectedFile();
            if (f==null)
                return;
            
            Scanner scn;       
            scn = new Scanner(f);
            String s="";
            while (scn.hasNext())
                s += scn.nextLine() + "\n";                
            
            textArea.setText(s);
            textArea.setCaretPosition(0);
        }catch(Exception e) {};
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        analex.avanzar();
        analex.resaltar();
        
        tfPreanalisis.setText(""+analex.Preanalisis());
        tfLexema.setText(analex.lexema());
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void tfPreanalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPreanalisisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPreanalisisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Interfaz form = new Interfaz();
                form.setLocationRelativeTo(null);  //Centrar el form
                form.setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnInit;
    private javax.swing.JButton btnOpen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLexema;
    private javax.swing.JLabel lblPreanalisis;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField tfLexema;
    private javax.swing.JTextField tfPreanalisis;
    // End of variables declaration//GEN-END:variables
}
